/var/log/nginx/*.log
/var/log/nginx/*/*.log
/var/www/*/storage/logs/*.log
/var/www/*/logs/*.log
{
    su root root
    size 6G
    rotate 10
    missingok
    compress
    compresscmd /usr/bin/nice
    compressoptions -n19 chrt --idle 0 ionice -c 3 /usr/bin/zstd --ultra -22 --long=31 --no-progress
    compressext .zst
    uncompresscmd /usr/bin/unzstd
    delaycompress
    notifempty
    create 0644 root root
    sharedscripts
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}
