/var/log/nginx/*.log
/var/log/nginx/*/*.log
/var/www/*/storage/logs/*.log
/var/www/*/logs/*.log
{
    su root root
    size 100M
    rotate 10
    missingok
    compress
    compresscmd /bin/gzip
    compressoptions -9
    delaycompress
    notifempty
    create 0644 root root
    sharedscripts
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}
